name: util_simple_3d
description: Utility for Sp3dObj. Includes 3D geometry generation utility and more.
version: 8.4.0
repository: https://github.com/MasahideMori-SimpleAppli/util_simple_3d

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_3d: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter