name: util_simple_3d
description: Utility for Sp3dObj.
version: 0.0.1
repository: https://github.com/MasahideMori1111/util_simple_3d

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_3d: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter