name: util_simple_3d
description: Utility for Sp3dObj. Includes 3D geometry generation utility and more.
version: 6.0.0
repository: https://github.com/MasahideMori-SimpleAppli/util_simple_3d

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_3d: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter